version: '3'

services:
  webserver:
    image: nginx:1.21-alpine
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./nginx/conf/:/etc/nginx/conf.d/:ro
      - ./certbot/www:/var/www/certbot/:ro
      - ./certbot/conf/:/etc/nginx/ssl/:ro
  certbot:
    image: certbot/certbot:latest
    volumes:
      - ./certbot/www/:/var/www/certbot/:rw
      - ./certbot/conf/:/etc/letsencrypt/:rw
  main:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: main
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
      - ./jobs/midnight:/etc/periodic/midnight
    ports:
      - '3000:3000'
    depends_on:
      - database
    env_file:
      - .env
  database:
    container_name: database
    image: mongo
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - '27017:27017'
