version: '3'

services:
  webserver:
    image: nginx:1.21-alpine
    ports:
      - 80:80
      - 443:443
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - ./dhparam:/etc/nginx/dhparam/:ro
      - ./certbot/conf:/etc/nginx/ssl/:ro
      - ./certbot/data/:/usr/share/nginx/html/letsencrypt/:ro
    depends_on:
      - main
  certbot:
    image: certbot/certbot:latest
    command: certonly --webroot --webroot-path=/usr/share/nginx/html/letsencrypt --email luifer.2341@gmail.com --agree-tos --no-eff-email -d easyrstate.com
    volumes:
      - ./certbot/conf/:/etc/letsencrypt/:rw
      - ./certbot/logs/:/var/log/letsencrypt/:rw
      - ./certbot/data/:/usr/share/nginx/html/letsencrypt/:rw
    depends_on:
      - webserver
  main:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: main
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
      - ./jobs/midnight:/etc/periodic/midnight
    ports:
      - '3000:3000'
    depends_on:
      - database
    env_file:
      - .env
  database:
    container_name: database
    image: mongo
    restart: always
    volumes:
      - ./data:/data/db
    ports:
      - '27017:27017'
