version: '3.4'

services:
  nginx:
    build:
      context: ../../
      dockerfile: ./docker/prod/Dockerfile.nginx
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./dhparam:/etc/nginx/dhparam
      - ./certbot/conf:/etc/nginx/ssl
      - ./certbot/data:/usr/share/nginx/html/letsencrypt
      - ../../nginx/nginx.sh:/nginx.sh
    depends_on:
      - main
    environment:
      - NGINX_HOST=easyrstate.com
  certbot:
    container_name: certbot
    image: certbot/certbot:latest
    command: certonly --webroot --webroot-path=/usr/share/nginx/html/letsencrypt --email contact@luifermoron.com --agree-tos --no-eff-email -d ${NGINX_HOST} --keep
    restart: always
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/logs:/var/log/letsencrypt
      - ./certbot/data:/usr/share/nginx/html/letsencrypt
    depends_on:
      - main
      - nginx
    environment:
      - NGINX_HOST=easyrstate.com
  main:
    build:
      context: ../../
      dockerfile: ./docker/prod/Dockerfile
    container_name: main
    volumes:
      - ../../:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
      - ../../jobs/midnight:/etc/periodic/midnight
    ports:
      - '3000:3000'
    depends_on:
      - database
    env_file:
      - .env
  database:
    container_name: database
    image: mongo
    restart: always
    volumes:
      - ../../data:/data/db
    ports:
      - '27017:27017'


