version: '3.4'

services:
  web:
    image: nginx:1.14.2-alpine
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./dhparam:/etc/nginx/dhparam
      - ./certbot/conf:/etc/nginx/ssl
      - ./certbot/data:/usr/share/nginx/html/letsencrypt
    depends_on:
      - main
  certbot:
    image: certbot/certbot:latest
    command: certonly --webroot --webroot-path=/usr/share/nginx/html/letsencrypt --email contact@luifermoron.com --agree-tos --no-eff-email -d luifermoron.com --keep
    volumes:
      - ./certbot/conf:/etc/letsencrypt
      - ./certbot/logs:/var/log/letsencrypt
      - ./certbot/data:/usr/share/nginx/html/letsencrypt
    depends_on:
      - main
      - web
  main:
    build:
      context: ../../
      dockerfile: ./docker/prod/Dockerfile
    container_name: main
    volumes:
      - ../../:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
      - ../../jobs/midnight:/etc/periodic/midnight
    ports:
      - '3000:3000'
    depends_on:
      - database
    env_file:
      - .env
  database:
    container_name: database
    image: mongo
    restart: always
    volumes:
      - ../../data:/data/db
    ports:
      - '27017:27017'
