- name: Install Docker and Docker Compose on Ubuntu
  become: true
  hosts: all
  tasks:
    - name: Update package list
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Install required packages
      apt:
        name:
          - apt-transport-https
          - curl
          - gnupg-agent
          - ca-certificates
          - software-properties-common
        state: present

    - name: Add Docker GPG key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker repository
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Install Docker
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present

    - name: Add user to docker group
      user:
        name: luifer_2341
        append: yes
        groups: docker

    - name: Reload group membership
      user:
        name: luifer_2341
        state: present
        groups: docker

    - name: Check Docker version
      command: docker version

    - name: Install Docker Compose
      file:
        path: ~/.docker/cli-plugins/
        state: directory

    - name: Download Docker Compose binary
      get_url:
        url: https://github.com/docker/compose/releases/download/v2.5.0/docker-compose-linux-x86_64
        dest: ~/.docker/cli-plugins/docker-compose
        mode: 'u+x'

    - name: Check Docker Compose version
      command: docker compose version
    - name: Copy SSH key pair
      become: true
      become_user: luifer_2341
      copy:
        src: '~/.ssh/id_test'
        dest: '~/.ssh/id_test'
        mode: '0600'
    - name: Copy public key
      become: true
      become_user: luifer_2341
      copy:
        src: '~/.ssh/id_test.pub'
        dest: '~/.ssh/id_test.pub'
        mode: '0644'
    - name: Start ssh-agent and add key
      become: true
      become_user: luifer_2341
      shell: |
        eval "$(ssh-agent -s)" 
        ssh-add ~/.ssh/id_test
    - name: Git clone
      become: true
      become_user: luifer_2341
      git:
        repo: git@github.com:easyRS/easyRS.git
        dest: ~/easyRS
        accept_hostkey: yes
        key_file: ~/.ssh/id_test
    - name: Checkout ft-docker-versions
      become: true
      become_user: luifer_2341
      command:
        cmd: git checkout origin/ft-docker-versions
        chdir: ~/easyRS
    - name: Create Default.conf
      become: true
      become_user: luifer_2341
      shell:
        cmd: |
          mkdir conf.d
          touch conf.d/default.conf
        chdir: ~/easyRS/docker/prod/nginx
    - name: Copy Certbot Conf Generation
      become: true
      become_user: luifer_2341
      copy:
        src: '~/easyRS/docker/prod/nginx/configs/cerbot-generation/default.conf'
        dest: '~/easyRS/docker/prod/nginx/conf.d/default.conf'
        remote_src: true
    - name: Set Docker socket permissions
      become: true
      become_user: root
      file:
        path: /var/run/docker.sock
        mode: '0777'
    - name: Generate Cerbot Certs
      become: true
      become_user: luifer_2341
      shell: |
        cd ~/easyRS
        docker compose -f docker/prod/docker-compose.yml up -d
    - name: Pause Docker Compose
      become: true
      become_user: luifer_2341
      shell: |
        cd ~/easyRS
        docker compose -f docker/prod/docker-compose.yml down
    - name: Copy Full Certbot Conf
      become: true
      become_user: luifer_2341
      copy:
        src: '~/easyRS/docker/prod/nginx/configs/full-conf/default.conf'
        dest: '~/easyRS/docker/prod/nginx/conf.d/default.conf'
        remote_src: true
    - name: Deploy Docker Compose
      become: true
      become_user: luifer_2341
      shell: |
        cd ~/easyRS
        docker compose -f docker/prod/docker-compose.yml up -d
