- name: Install Docker and Docker Compose on Ubuntu
  become: true
  hosts: all
  tasks:
    - name: Update package list
      apt:
        update_cache: yes
        cache_valid_time: 3600
    - name: Install required packages
      apt:
        name:
          - apt-transport-https
          - curl
          - gnupg-agent
          - ca-certificates
          - software-properties-common
        state: present
    - name: Copy SSH key pair
      become: true
      become_user: luifer_2341
      copy:
        src: '~/.ssh/id_test'
        dest: '~/.ssh/id_test'
        mode: '0600'
    - name: Copy public key
      become: true
      become_user: luifer_2341
      copy:
        src: '~/.ssh/id_test.pub'
        dest: '~/.ssh/id_test.pub'
        mode: '0644'
    - name: Start ssh-agent and add key
      become: true
      become_user: luifer_2341
      shell: |
        eval "$(ssh-agent -s)" 
        ssh-add ~/.ssh/id_test
    - name: Git clone
      become: true
      become_user: luifer_2341
      git:
        repo: git@github.com:easyRS/easyRS.git
        dest: ~/easyRS
        accept_hostkey: yes
        key_file: ~/.ssh/id_test
    - name: Checkout ft-ansible-configuration
      become: true
      become_user: luifer_2341
      command:
        cmd: git checkout origin/ft-ansible-configuration
        chdir: ~/easyRS
    - name: Copy Certbot Conf Generation
      become: true
      become_user: luifer_2341
      copy:
        src: '~/easyRS/nginx/configs/cerbot-generation/default.conf'
        dest: '~/easyRS/nginx/conf.d/default.conf'
        remote_src: true
