- name: Update code base and run type seeders only
  become: true
  become_user: '{{ ansible_user }}'
  hosts: all
  tasks:
    - name: Copy SSH key pair
      become: true
      become_user: '{{ ansible_user }}'
      copy:
        src: '~/.ssh/{{ SSH_KEY }}'
        dest: '~/.ssh/{{ SSH_KEY }}'
        mode: '0600'
    - name: Copy public key
      become: true
      become_user: '{{ ansible_user }}'
      copy:
        src: '~/.ssh/{{ SSH_KEY }}.pub'
        dest: '~/.ssh/{{ SSH_KEY }}.pub'
        mode: '0644'
    - name: Start ssh-agent and add key
      become: true
      become_user: '{{ ansible_user }}'
      shell: |
        eval "$(ssh-agent -s)" 
        ssh-add ~/.ssh/{{ SSH_KEY }}
    - name: Pause Docker Compose
      become: true
      become_user: '{{ ansible_user }}'
      shell: |
        cd ~/easyRS
        docker compose -f docker/prod/docker-compose.yml down
    - name: Pull changes
      become: true
      become_user: '{{ ansible_user }}'
      git:
        repo: git@github.com:easyRS/easyRS.git
        dest: ~/easyRS
        remote: origin
        version: ft-update-playbook
        update: yes
        accept_hostkey: yes
        key_file: ~/.ssh/{{ SSH_KEY }}
    - name: Deploy Docker Compose
      become: true
      become_user: '{{ ansible_user }}'
      shell: |
        cd ~/easyRS
        docker compose -f docker/prod/docker-compose.yml up --build -d
    - name: Run seeders
      become: true
      become_user: '{{ ansible_user }}'
      shell: |
        cd ~/easyRS
        docker exec main yarn run seed --seed_fake_data=false --delete_data=false --seed_types=true
